service: ocr
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  region: us-east-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:GetObject
          Resource:
            - arn:aws:s3:::htnx-method/*


functions:
  ocr:
    handler: handler.lambda_handler
    events:
      - s3:
          bucket: htnx-method
          event: s3:ObjectCreated:*

custom:
  pythonRequirements:
    dockerizePip: true
