import './globals.css';
import { UserProvider } from './context/UserContext';

export const metadata = {
  title: 'OneHireHelp',
  description: 'Generated by Next.js',
}
 
export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <UserProvider>
      <body>{children}</body>    
      </UserProvider>
    </html>
  )
}
