# Generated by Django 4.2.5 on 2023-09-16 23:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobapplications',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='jobapplications',
            unique_together={('job', 'user')},
        ),
    ]
